name: Deploy to GitHub Pages

on:
  - push

jobs:
  deploy:
    name: Angular CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Deploy to Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/clashsoft-apps/browser/
          cname: app.clashsoft.de
